### ISSUE TITLE
Nix gray background?

### ISSUE THREAD

**Issue by remexre** [acmumn/website-old#17]
events page looks ugly af

**Comment by mzhang28** [comment]
screenshot @ ugliness?

**Comment by remexre** [comment]
![](https://imgur.com/zM0QTnE.png)

**Comment by mzhang28** [comment]
i can't reproduce this. what style is causing that for u?

**Comment by remexre** [comment]
No clue... I poked for a while, couldn't find anything.

**Comment by mzhang28** [comment]
closed cus ur system colors r stoopd

**Comment by remexre** [comment]
Maybe set the body background color explicitly, given that this isn't a
problem on e.g. Google? and that it's caused by a non-user-made change that
happens with Firefox default settings...
